spring:
  application:
    name: cen-edu
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cen_edu}
    username: ${DB_USERNAME:cen}
    password: ${DB_PASSWORD:cen_local_password}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}
